### 55 / Create a Pandas DataFrame from the following table and write code to remove all rows from this table containing at least one notnull value

In [11]:
import pandas as pn
import numpy as np
data={
    "name":["William","Emma","Sofia","Markus","Edward","Thomas","Ethan",np.nan,"Arun","Anika","Paulo"],
    "region":[np.nan,"North","East",np.nan,"West","West","South",np.nan,"West","East","South"],
    "sales":[50000,52000,np.nan,np.nan,42000,72000,49000,np.nan,67000,65000,67000],
    "expenses":[42000,43000,np.nan,np.nan,38000,39000,42000,np.nan,39000,50000,45000]
    
     }
df=pn.DataFrame(data)
df=df.dropna()

df

      name region    sales  expenses
1     Emma  North  52000.0   43000.0
4   Edward   West  42000.0   38000.0
5   Thomas   West  72000.0   39000.0
6    Ethan  South  49000.0   42000.0
8     Arun   West  67000.0   39000.0
9    Anika   East  65000.0   50000.0
10   Paulo  South  67000.0   45000.0

### 56 / Create a Pandas DataFrame from the following table and write code to remove all rows from this table only if all of their values are NaN

In [12]:
import pandas as pn
import numpy as np
data={
    "name":["William","Emma","Sofia","Markus","Edward","Thomas","Ethan",np.nan,"Arun","Anika","Paulo"],
    "region":[np.nan,"North","East",np.nan,"West","West","South",np.nan,"West","East","South"],
    "sales":[50000,52000,np.nan,np.nan,42000,72000,49000,np.nan,67000,65000,67000],
    "expenses":[42000,43000,np.nan,np.nan,38000,39000,42000,np.nan,39000,50000,45000]
    
     }
df=pn.DataFrame(data)
df=df.dropna(how="all")

df

       name region    sales  expenses
0   William    NaN  50000.0   42000.0
1      Emma  North  52000.0   43000.0
2     Sofia   East      NaN       NaN
3    Markus    NaN      NaN       NaN
4    Edward   West  42000.0   38000.0
5    Thomas   West  72000.0   39000.0
6     Ethan  South  49000.0   42000.0
8      Arun   West  67000.0   39000.0
9     Anika   East  65000.0   50000.0
10    Paulo  South  67000.0   45000.0

### 57 / Create a Pandas DataFrame from the following table and write code to drop all columns containing NaN

In [14]:
import pandas as pn
import numpy as np
data={
    "name":["William","Emma","Sofia","Markus","Edward","Thomas","Ethan",np.nan,"Arun","Anika","Paulo"],
    "region":[np.nan,"North","East",np.nan,"West","West","South",np.nan,"West","East","South"],
    "sales":[50000,52000,np.nan,np.nan,42000,72000,49000,np.nan,67000,65000,67000],
    "expenses":[42000,43000,np.nan,np.nan,38000,39000,42000,np.nan,39000,50000,45000]
    
     }
df=pn.DataFrame(data)
df=df.dropna(axis=1)

df

Empty DataFrame
Columns: []
Index: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

### 58 / Write Python code to remove outliers from any given DataFrame

In [21]:
''' 59 / Consider the following data:
data = {
    "A": ["TeamA", "TeamB", "TeamB", "TeamC", "TeamA"],
    "B": [50, 40, 40, 30, 50],
    "C": [True, False, False, False, True]
}
Convert this to a Pandas DataFrame and remove duplicate rows from it. Reset index values.'''
import pandas as pn
import numpy as np
data = {
    "A": ["TeamA", "TeamB", "TeamB", "TeamC", "TeamA"],
    "B": [50, 40, 40, 30, 50],
    "C": [True, False, False, False, True]
}
df=pn.DataFrame(data)
df=df.drop_duplicates()
df.reset_index()
df

       A   B      C
0  TeamA  50   True
1  TeamB  40  False
3  TeamC  30  False

In [22]:
'''
onsider the following autompg dataset:
https://raw.githubusercontent.com/Jovita7/Data-Analysis-and-Visualization/main/auto-mpg.csv
Write Python code to convert it to a DataFrame and remove mpg and cylinders columns from it 
'''
import pandas as pd

url = "https://raw.githubusercontent.com/Jovita7/Data-Analysis-and-Visualization/main/auto-mpg.csv"
df = pd.read_csv(url)

df = df.drop(['mpg', 'cylinders'], axis=1)

df

,displacement,horsepower,weight,acceleration,model year,origin,car name
0,307.0,130,3504,12.0,70,1,chevrolet chevelle malibu
1,350.0,165,3693,11.5,70,1,buick skylark 320
2,318.0,150,3436,11.0,70,1,plymouth satellite
3,304.0,150,3433,12.0,70,1,amc rebel sst
4,302.0,140,3449,10.5,70,1,ford torino
...,...,...,...,...,...,...,...
393,140.0,86,2790,15.6,82,1,ford mustang gl
394,97.0,52,2130,24.6,82,2,vw pickup
395,135.0,84,2295,11.6,82,1,dodge rampage
396,120.0,79,2625,18.6,82,1,ford ranger
397,119.0,82,2720,19.4,82,1,chevy s-10

In [23]:
import pandas as pn 
url="https://raw.githubusercontent.com/Jovita7/Data-Analysis-and-Visualization/main/heights_weights.csv"
df=pn.read_csv(url)
df

         Height      Weight  Male
0     73.847017  241.893563     1
1     68.781904  162.310473     1
2     74.110105  212.740856     1
3     71.730978  220.042470     1
4     69.881796  206.349801     1
...         ...         ...   ...
9995  66.172652  136.777454     0
9996  67.067155  170.867906     0
9997  63.867992  128.475319     0
9998  69.034243  163.852461     0
9999  61.944246  113.649103     0

[10000 rows x 3 columns]